-- Add missing columns to popular_jobs table
ALTER TABLE popular_jobs
ADD COLUMN IF NOT EXISTS title_kh VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS description_kh TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS salary_range VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS requirements TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS image_path VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_active TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 0;

-- Add missing columns to popular_majors table
ALTER TABLE popular_majors
ADD COLUMN IF NOT EXISTS title_kh VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS description_kh TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS institutions TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS skills_gained TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS image_path VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_active TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 0;

-- Add missing columns to career_paths table
ALTER TABLE career_paths
ADD COLUMN IF NOT EXISTS title_kh VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS description_kh TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS progression_steps TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS required_education TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS image_path VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_active TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 0;
